"""optional reason

Revision ID: 4887279e98ea
Revises: 91f637ea3abd
Create Date: 2026-05-10 22:25:06.784056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4887279e98ea'
down_revision: Union[str, Sequence[str], None] = '91f637ea3abd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('service_orders_status_histories', 'reason',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('service_orders_status_histories', 'reason',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
