"""work sessions total hours

Revision ID: bba5a1f25e1a
Revises: 4887279e98ea
Create Date: 2026-05-27 22:56:22.945056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bba5a1f25e1a'
down_revision: Union[str, Sequence[str], None] = '4887279e98ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_sessions', sa.Column('total_hours', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_sessions', 'total_hours')
    # ### end Alembic commands ###
