"""employees table 2

Revision ID: cce69fa6e492
Revises: 7478addb87e2
Create Date: 2026-04-29 06:29:25.527639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cce69fa6e492'
down_revision: Union[str, Sequence[str], None] = '7478addb87e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('admission_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'on_vacation', 'sick_leave', name='employeestatus'), nullable=False),
    sa.Column('type', sa.Enum('independent', 'employee', name='employeetype'), nullable=False),
    sa.Column('payment_method', sa.Enum('monthly', 'weekly', 'daily', name='paymentmethod'), nullable=False),
    sa.Column('payment_value', sa.Float(), nullable=False),
    sa.Column('hourly_rate', sa.Float(), nullable=True),
    sa.Column('hourly_bonus', sa.Float(), nullable=True),
    sa.Column('observations', sa.String(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('updated_at', sa.Date(), nullable=True),
    sa.Column('deleted_at', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employees')
    # ### end Alembic commands ###
