"""employee position relation

Revision ID: d801956ac48e
Revises: cce69fa6e492
Create Date: 2026-04-29 08:41:42.386543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd801956ac48e'
down_revision: Union[str, Sequence[str], None] = 'cce69fa6e492'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('position_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'employees', 'positions', ['position_id'], ['id'])
    op.add_column('positions', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('positions', 'description')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_column('employees', 'position_id')
    # ### end Alembic commands ###
